### PR TITLE
Make thread-safe; use JLL package

### LINKED ISSUE #39: Make DecFP package thread safe
Although the multithreading support in Julia v0.6 is still classified as experimental, I assume that the goal is to have it fully working (and have packages work correctly when threads are used) by the time v1.0 is released.
Currently, the DecFP uses a single buffer (`_buffer`) used when converting a decimal to a string,
as well as C globals for rounding mode and exception flags.
When using threads, the buffer would need to be stored in thread-local storage or locking used when using the buffer, and the rounding mode and exception flags would need to also be in thread-local storage (and the Intel package compiled to pass those on every call instead of using global values).

### PR DESCRIPTION
**Pull request by jmkuhn**
Fixes #39 #47.

### CODE REVIEW

**Comment by jmkuhn** [comment]
Even though this passes, don't merge.  It looks like the way I am defining my global arrays precompiles with the value of Threads.ntheads() from the first time I run it.

File: src/DecFP.jl [hunk 1]
```diff
@@ -82,13 +75,18 @@ function Base.convert(::Type{RoundingMode}, r::DecFPRoundingMode)
     end
 end
 
-const ROUNDING_PTR = Ref{Ptr{DecFPRoundingMode}}()
+const roundingmode = Vector{DecFPRoundingMode}()
```
Comment (quinnj) [inline src/DecFP.jl]: It's more idiomatic to say `= DecFPRoundingMode[]`

File: src/DecFP.jl [hunk 2]
```diff
@@ -82,13 +75,18 @@ function Base.convert(::Type{RoundingMode}, r::DecFPRoundingMode)
...
-    global ROUNDING_PTR[] = cglobal((:__bid_IDEC_glbround, libbid), DecFPRoundingMode) # rounding mode
-    global flags[] = cglobal((:__bid_IDEC_glbflags, libbid), Cuint) # exception status
-    unsafe_store!(flags[], 0)
+    resize!(_buffer, Threads.nthreads())
+    resize!(flags, Threads.nthreads())
+    resize!(roundingmode, Threads.nthreads())
+    for i = 1:Threads.nthreads()
+        global _buffer[i] = fill(0x00, 1024)
+        global flags[i] = [0x00000000]
+        global roundingmode[i] = DecFPRoundNearest
```
Comment (stevengj) [inline src/DecFP.jl]: You don't need the `global` annotation here, since you aren't mutating a global variable.  (You are calling `setindex!` on a global variable, which is not the same thing.

File: src/DecFP.jl [hunk 3]
```diff
@@ -205,10 +203,10 @@ for w in (32,64,128)
...
     @eval begin
         _parse(::Type{$BID}, s::AbstractString) =
-            ccall(($(bidsym(w,"from_string")), libbid), $BID, (Ptr{UInt8},), s)
-        _nextfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128), x, pinf128)
-        _prevfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128), x, minf128)
-        _sub(x::$BID, y::$BID) = ccall(($(bidsym(w,"sub")), libbid), $BID, ($BID,$BID), x, y)
+            ccall(($(bidsym(w,"from_string")), libbid), $BID, (Ptr{UInt8},Cuint,Ref{Cuint}), s, DecFPRoundNearest, _flags)
+        _nextfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128,Ref{Cuint}), x, pinf128, _flags)
+        _prevfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128,Ref{Cuint}), x, minf128, _flags)
+        _sub(x::$BID, y::$BID) = ccall(($(bidsym(w,"sub")), libbid), $BID, ($BID,$BID,Cuint,Ref{Cuint}), x, y, DecFPRoundNearest, _flags)
```
Comment (stevengj) [inline src/DecFP.jl]: This doesn't seem right.

For example, since `Base.parse` calls `_parse`, doesn't this mean that `Base.parse` isn't thread-safe?

File: src/DecFP.jl [hunk 4]
```diff
@@ -1,30 +1,23 @@
...
 import Base.promote_rule
 
-#############################################################################
-# exception handling via global flags
-# (todo: recompile library with GLOBAL_FLAGS=0 for thread-safety)
-
-const flags = Ref{Ptr{Cuint}}() # set to __bid_IDEC_glbflags in __init__
+# flags isn't defined until __init__ runs
+const _flags = [0x00000000]
+const flags = Vector{Vector{Cuint}}()
```
Comment (stevengj) [inline src/DecFP.jl]: Seems like we could just do:
```jl
const flags = [Ref(0x00000000)]
```
and then resize `flags` in `__init__`.   Code that currently uses `_flags` could use `flags[Threads.threadid()]` instead, since during precompilation we will always have `threadid() == 1` and so it won't matter if `__init__` hadn't run yet.

File: src/DecFP.jl [hunk 5]
```diff
@@ -1,30 +1,23 @@
...
 
 # clear exception flags and return x
 function nox(x)
-    unsafe_store!(flags[], 0)
+    flags[Threads.threadid()][1] = 0
```
Comment (stevengj) [inline src/DecFP.jl]: (with my suggestion above, you would use `[]` instead).

File: src/DecFP.jl (hunk 4 above)
Comment (stevengj) [reply src/DecFP.jl]: Alternatively, we could use `flags = [0x00000000]`, which avoids the double indirection.   Then, you would pass `Base.RefArray(flags, Threads.threadid())` to any `ccall` needing a `Ref{Cuint}`.

Comment (jmkuhn) [reply src/DecFP.jl]: Yes, using `flags = [0x00000000]` and `RefArray(flags, Threads.threadid())` is slightly faster than `flags = [Ref(0x00000000)]`.
```
julia> @btime abs($x)
  6.564 ns (0 allocations: 0 bytes)
1.0
```
vs
```
julia> @btime abs($x)
  6.830 ns (0 allocations: 0 bytes)
1.0
```

File: src/DecFP.jl (hunk 3 above)
Comment (jmkuhn) [reply src/DecFP.jl]: Both `_parse` and `Base.parse` are now thread-safe.

**Comment by quinnj** [comment]
Bump, is this good to go now?

**Comment by jmkuhn** [comment]
I believe this is good to go.

**Comment by ViralBShah** [comment]
Merge?

File: src/DecFP.jl [hunk 6]
```diff
@@ -205,10 +201,10 @@ for w in (32,64,128)
...
     @eval begin
         _parse(::Type{$BID}, s::AbstractString) =
-            ccall(($(bidsym(w,"from_string")), libbid), $BID, (Ptr{UInt8},), s)
-        _nextfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128), x, pinf128)
-        _prevfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128), x, minf128)
-        _sub(x::$BID, y::$BID) = ccall(($(bidsym(w,"sub")), libbid), $BID, ($BID,$BID), x, y)
+            ccall(($(bidsym(w,"from_string")), libbid), $BID, (Ptr{UInt8},Cuint,Ref{Cuint}), s, roundingmode[Threads.threadid()], RefArray(flags, Threads.threadid()))
+        _nextfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128,Ref{Cuint}), x, pinf128, RefArray(flags, Threads.threadid()))
+        _prevfloat(x::$BID) = ccall(($(bidsym(w,"nexttoward")), libbid), $BID, ($BID,Dec128,Ref{Cuint}), x, minf128, RefArray(flags, Threads.threadid()))
+        _sub(x::$BID, y::$BID) = ccall(($(bidsym(w,"sub")), libbid), $BID, ($BID,$BID,Cuint,Ref{Cuint}), x, y, DecFPRoundNearest, RefArray(flags, Threads.threadid()))
```
Comment (stevengj) [inline src/DecFP.jl]: Why not `roundingmode[Threads.threadid()]`?

File: src/DecFP.jl [hunk 7]
```diff
@@ -224,44 +220,44 @@ for w in (32,64,128)
...
             # fills global _buffer
-            ccall(($(bidsym(w,"to_string")), libbid), Cvoid, (Ptr{UInt8}, $BID), _buffer, x)
+            ccall(($(bidsym(w,"to_string")), libbid), Cvoid, (Ptr{UInt8},$BID,Ref{Cuint}), _buffer[Threads.threadid()], x, RefArray(flags, Threads.threadid()))
         end
 
         function Base.show(io::IO, x::$BID)
             isnan(x) && (print(io, "NaN"); return)
             isinf(x) && (print(io, signbit(x) ? "-Inf" : "Inf"); return)
             x == 0 && (print(io, signbit(x) ? "-0.0" : "0.0"); return)
             tostring(x)
```
Comment (stevengj) [inline src/DecFP.jl]: I would just set `buffer = `_buffer[Threads.threadid()]` and then use `buffer` throughout the function.

File: src/DecFP.jl [hunk 8]
```diff
@@ -224,44 +220,44 @@ for w in (32,64,128)
...
-            lastdigitindex = findfirst(isequal(UInt8('E')), _buffer) - 1
-            lastnonzeroindex = findlast(!isequal(UInt8('0')), view(_buffer, 1:lastdigitindex))
+            lastdigitindex = findfirst(isequal(UInt8('E')), _buffer[Threads.threadid()]) - 1
+            lastnonzeroindex = findlast(!isequal(UInt8('0')), view(_buffer[Threads.threadid()], 1:lastdigitindex))
             if -5 < normalized_exponent < 6
                 # %f
                 if normalized_exponent >= 0
                     if normalized_exponent >= lastnonzeroindex - 2
-                        GC.@preserve _buffer unsafe_write(io, pointer(_buffer, 2), lastnonzeroindex - 1)
+                        GC.@preserve _buffer unsafe_write(io, pointer(_buffer[Threads.threadid()], 2), lastnonzeroindex - 1)
```
Comment (stevengj) [inline src/DecFP.jl]: (Use `GC.@preserve buffer` with my suggestion above.)

**Comment by jmkuhn** [comment]
I'm not sure what the issue is with the Windows nightly runs, but I don't think it is related to this PR.
