### PR TITLE
Fix Irrational and BigFloat comparisons

### LINKED ISSUE #122: Comparison with Irrational
```
julia> BigFloat(π)
3.141592653589793238462643383279502884197169399375105820974944592307816406286198

julia> Dec128(π)
3.141592653589793238462643383279503

julia> Dec128(π) > π
false

julia> Dec128(π) < π
false

julia> Dec128(π) == π
false
```

### PR DESCRIPTION
**Pull request by jmkuhn**
For Irrational comparisions ==, <=, >= we are using Base functions:
==(x::Real, y::AbstractIrrational) = false
<=(x::AbstractFloat, y::AbstractIrrational) = x < y
etc

Fixes #122

### CODE REVIEW

File: src/DecFP.jl [hunk 1]
```diff
@@ -758,18 +760,18 @@ function Base.:(==)(dec::DecimalFloatingPoint, rat::Rational)
...
-Base.:>(dec::T, flt::Union{Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec > T(flt, RoundDown)
-Base.:<(dec::T, flt::Union{Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec < T(flt, RoundUp)
-Base.:(>=)(dec::T, flt::Union{Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec >= T(flt, RoundUp)
-Base.:(<=)(dec::T, flt::Union{Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec <= T(flt, RoundDown)
+Base.:(==)(dec::T, num::Union{BigFloat,Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec == T(num, RoundUp) == T(num, RoundDown)
+Base.:>(dec::T, num::Union{BigFloat,Float16,Float32,Float64,Integer,AbstractIrrational}) where {T<:DecimalFloatingPoint} = dec > T(num, RoundDown)
+Base.:<(dec::T, num::Union{BigFloat,Float16,Float32,Float64,Integer,AbstractIrrational}) where {T<:DecimalFloatingPoint} = dec < T(num, RoundUp)
+Base.:(>=)(dec::T, num::Union{BigFloat,Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec >= T(num, RoundUp)
+Base.:(<=)(dec::T, num::Union{BigFloat,Float16,Float32,Float64,Integer}) where {T<:DecimalFloatingPoint} = dec <= T(num, RoundDown)
```
Comment (stevengj) [inline src/DecFP.jl:767]: Shouldn't `<=` and `>=` support `AbstractIrrational` too?

Comment (jmkuhn) [reply src/DecFP.jl:767]: This is using the methods from Base Irrational.jl
```
<=(x::AbstractFloat, y::AbstractIrrational) = x < y
```
etc.  If I add `AbstractIrrational` here I get method ambiguities:
```
julia> Dec64(π) <= π
ERROR: MethodError: <=(::Dec64, ::Irrational{:π}) is ambiguous. Candidates:
  <=(x::AbstractFloat, y::AbstractIrrational) in Base at irrationals.jl:106
  <=(dec::T, num::Union{Float16, Float32, Float64, AbstractIrrational, Integer, BigFloat}) where T<:DecFP.DecimalFloatingPoint in DecFP at /Users/john.m.kuhn/julia_dev/DecFP_irrational/dev/DecFP/src/DecFP.jl:767
Possible fix, define
  <=(::T, ::AbstractIrrational) where T<:DecFP.DecimalFloatingPoint
```
