### PR TITLE
read and write methods. Fixes #160

### LINKED ISSUE #160: Serialization broken after change to primitive types
```
julia> using DecFP, Serialization
julia> serialize(IOBuffer(), one(Dec64))
ERROR: MethodError: no method matching write(::IOBuffer, ::Dec64)
Closest candidates are:
  write(::IO, ::Any) at io.jl:635
  write(::IO, ::Any, ::Any...) at io.jl:636
  write(::AbstractString, ::Any, ::Any...) at io.jl:420
  ...
Stacktrace:
 [1] write(io::IOBuffer, x::Dec64)
   @ Base ./io.jl:635
 [2] serialize_any(s::Serializer{IOBuffer}, x::Any)
   @ Serialization /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Serialization/src/Serialization.jl:647
 [3] serialize
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Serialization/src/Serialization.jl:636 [inlined]
 [4] serialize(s::IOBuffer, x::Dec64)
   @ Serialization /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Serialization/src/Serialization.jl:745
 [5] top-level scope
   @ REPL[99]:1
```

### PR DESCRIPTION
**Pull request by dantaras**

### CODE REVIEW

File: src/DecFP.jl [hunk 1]
```diff
@@ -140,6 +140,8 @@ struct Dec128 <: DecimalFloatingPoint
 end
 Base.reinterpret(::Type{UInt128}, x::Dec128) = x.x
 Base.bswap(x::Dec128) = reinterpret(Dec128, bswap(x.x))
+Base.write(s::IO, x::Union{Dec32, Dec64, Dec128}) = write(s, Ref(x))
```
Comment (stevengj) [inline src/DecFP.jl:143]: Maybe better to use
```jl
Base.write(io::IO, x::$BID) = write(io, reinterpret($Ti, x))
Base.read(io::IO, x::Type{$BID}) = reinterpret($BID, read(io, $Ti))
```
inside the `for w in (32,64,128)` loop to avoid the `Ref` overhead?

File: test/runtests.jl [hunk 2]
```diff
@@ -457,6 +457,11 @@ for T in (Dec32, Dec64, Dec128)
 
     # issue #85
     @test T(1.5) == T(T(1.5))
+
+    # issue 160
+    io = IOBuffer()
+    write(io, one(T))
+    @test read(IOBuffer(take!(io)), T) == one(T)
```
Comment (stevengj) [inline test/runtests.jl:464]:
```suggestion
    @test read(IOBuffer(take!(io)), T) === one(T)
```

File: src/DecFP.jl (hunk 1 above)
Comment (dantaras) [reply src/DecFP.jl]: Done. Worth noting that `Ref` is used inside Julia primitive types `read`/`write` so the overhead should be mostly the same. https://github.com/JuliaLang/julia/blob/v1.7.2/base/io.jl#L651-L653

**Comment by stevengj** [comment]
LGTM, thanks!
