### PR TITLE
Printf: avoid converting to Float64 or BigFloat

### LINKED ISSUE #178: printf is converting to `Float64`
It looks like the `@printf` macro is broken — it seems to be converting values to `Float64` before printing (reported [on discourse](https://discourse.julialang.org/t/printf-with-decfp-dec128/108996)):
```jl
julia> using DecFP, Printf

julia> x = rand(Dec128)
0.6498353664629435612857337361220566

julia> println(x)
0.6498353664629435612857337361220566

julia> @printf("%.36f", x)
0.649835366462943597731793943239608780
julia> 

julia> @printf("%.36f\n", Float64(x)) # matches @printf("%.36f", x) !!
0.649835366462943597731793943239608780
```
@jmkuhn, has `@printf` bitrotted?  I thought it used to be working (after #48).

### PR DESCRIPTION
**Pull request by jmkuhn**
Fixes #178

Currently Printf is converting `DecimalFloatingPoint` values to `Float64` which causes issues such as
```
julia> @sprintf("%.36f", d64"0.1")
"0.100000000000000005551115123125782702"

julia> @sprintf("%e", floatmax(Dec64))
"Inf"
```
With this PR
```
julia> @sprintf("%.36f", d64"0.1")
"0.100000000000000000000000000000000000"

julia> @sprintf("%e", floatmax(Dec64))
"1.000000e+385"
```
Currently %a/%A formatting isn't implemented.  I'll do that in a separate PR.

@quinnj

### CODE REVIEW

File: src/DecFP.jl [hunk 1]
```diff
@@ -791,6 +720,292 @@ promote_rule(::Type{Irrational{s}}, T::Type{Complex{F}}) where {s,F<:DecimalFloa
 Base.widen(::Type{Dec32}) = Dec64
 Base.widen(::Type{Dec64}) = Dec128
 
+# Printf
```
Comment (stevengj) [inline src/DecFP.jl:723]: Maybe have a separate file `printf.jl` that we just `include` here?

Comment (stevengj) [reply src/DecFP.jl:723]: But I'm fine with merging this now and re-organizing in a separate PR…

Comment (jmkuhn) [reply src/DecFP.jl:723]: I'll reorganize this weekend.  Don't merge yet.

Comment (jmkuhn) [reply src/DecFP.jl]: I have split out into `printf.jl` for both src and test.

**Review by stevengj — APPROVED** [review]

**Comment by stevengj** [comment]
LGTM.  Merge when ready.

**Comment by jmkuhn** [comment]
Looks like I no longer have write access to merge.  It is ready to merge.

**Comment by stevengj** [comment]
I added you to the repo so that you should be able to merge in the future.
